# Generated by Django 4.1 on 2022-09-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_counting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='points number')),
            ],
        ),
    ]
