# Generated by Django 4.1 on 2022-09-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_counting', '0002_pointsnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_text', models.CharField(max_length=50, verbose_name='payer name')),
                ('paid', models.IntegerField(verbose_name='points paid')),
                ('left', models.IntegerField(verbose_name='points left to pay')),
            ],
        ),
    ]
