# Generated by Django 4.1 on 2022-09-05 05:27

from django.db import migrations


def create_data_from_example(apps, schema_editor):
    Transaction = apps.get_model('points_counting', 'Transaction')
    transaction = Transaction(payer_text='DANNON', points=1000, date='2020-11-02T14:00:00Z')
    transaction.save()
    transaction = Transaction(payer_text='UNILEVER', points=200, date='2020-10-31T11:00:00Z')
    transaction.save()
    transaction = Transaction(payer_text='DANNON', points=-200, date='2020-10-31T15:00:00Z')
    transaction.save()
    transaction = Transaction(payer_text='MILLER COORS', points=10000, date='2020-11-01T14:00:00Z')
    transaction.save()
    transaction = Transaction(payer_text='DANNON', points=300, date='2020-10-31T10:00:00Z')
    transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('points_counting', '0003_payer'),
    ]

    operations = [
        migrations.RunPython(create_data_from_example),
    ]
